
import React from 'react';
import { useApp } from '../contexts/AppContext';
import { Mail, ArrowLeft, Trash2, RefreshCw } from 'lucide-react';

export const SimulatedInbox: React.FC = () => {
    const { emailLogs, emailSystemStatus } = useApp();

    return (
        <div className="h-full flex flex-col bg-maestro-900">
            <header className="p-6 border-b border-maestro-700 flex justify-between items-center bg-maestro-800">
                <div>
                    <h1 className="text-3xl font-bold text-white flex items-center gap-3">
                        <Mail className="w-8 h-8 text-maestro-accent" /> Simulated Inbox
                    </h1>
                    <p className="text-slate-400">View emails generated by the system (Simulation Mode)</p>
                </div>
                <div className="flex items-center gap-3">
                    <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase ${
                        emailSystemStatus === 'ENABLED' ? 'bg-green-900 text-green-400' :
                        emailSystemStatus === 'SIMULATION' ? 'bg-blue-900 text-blue-400' :
                        'bg-red-900 text-red-400'
                    }`}>
                        Gateway: {emailSystemStatus}
                    </span>
                </div>
            </header>

            <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">
                {emailLogs.length === 0 ? (
                    <div className="flex flex-col items-center justify-center h-full text-slate-500">
                        <Mail className="w-16 h-16 mb-4 opacity-20" />
                        <p>No emails have been sent yet.</p>
                        <p className="text-sm">Trigger an action (e.g. Reset Password, Invite User) to see it here.</p>
                    </div>
                ) : (
                    <div className="space-y-4 max-w-4xl mx-auto">
                        {emailLogs.map((log) => (
                            <div key={log.id} className="bg-maestro-800 rounded-xl border border-maestro-700 overflow-hidden shadow-lg animate-fadeIn">
                                <div className="p-4 border-b border-maestro-700 flex justify-between items-start bg-maestro-900/50">
                                    <div className="flex-1">
                                        <div className="flex items-center gap-2 mb-1">
                                            <span className="text-xs font-bold text-slate-500 uppercase w-12">To:</span>
                                            <span className="text-maestro-accent font-mono text-sm">{log.to}</span>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <span className="text-xs font-bold text-slate-500 uppercase w-12">Subject:</span>
                                            <span className="text-white font-bold">{log.subject}</span>
                                        </div>
                                    </div>
                                    <div className="text-right">
                                        <div className="text-xs text-slate-500 font-mono">{new Date(log.timestamp).toLocaleString()}</div>
                                        <span className={`inline-block mt-2 px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                                            log.status === 'SENT' ? 'bg-green-900/50 text-green-400' :
                                            log.status === 'QUEUED' ? 'bg-blue-900/50 text-blue-400' :
                                            'bg-red-900/50 text-red-400'
                                        }`}>
                                            {log.status}
                                        </span>
                                    </div>
                                </div>
                                <div className="p-6 text-slate-300 text-sm whitespace-pre-wrap leading-relaxed font-sans bg-maestro-800">
                                    {log.body}
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
};
